response_fixture = {
    "response": {
        "status": "ok",
        "userTier": "developer",
        "total": 2556540,
        "startIndex": 1,
        "pageSize": 10,
        "currentPage": 1,
        "pages": 255654,
        "orderBy": "newest",
        "results": [
            {
                "id": "politics/live/2024/dec/10/uk-politics-live-rachel-reeves-spending-review-keir-starmer-cyprus",
                "type": "liveblog",
                "sectionId": "politics",
                "sectionName": "Politics",
                "webPublicationDate": "2024-12-10T17:06:03Z",
                "webTitle": "UK politics live: Kemi Badenoch criticised by",
                "webUrl": "https://www.theguardian.com/politics/live/2024/dec/10/uk-politics-live-rachel-reeves-spending-review-keir-starmer-cyprus",
                "apiUrl": "https://content.guardianapis.com/politics/live/2024/dec/10/uk-politics-live-rachel-reeves-spending-review-keir-starmer-cyprus",
                "isHosted": False,
                "pillarId": "pillar/news",
                "pillarName": "News",
            },
            {
                "id": "football/live/2024/dec/10/girona-v-liverpool-champions-league-live-score-updates",
                "type": "liveblog",
                "sectionId": "football",
                "sectionName": "Football",
                "webPublicationDate": "2024-12-10T17:02:46Z",
                "webTitle": "Girona v Liverpool: Champions League – live",
                "webUrl": "https://www.theguardian.com/football/live/2024/dec/10/girona-v-liverpool-champions-league-live-score-updates",
                "apiUrl": "https://content.guardianapis.com/football/live/2024/dec/10/girona-v-liverpool-champions-league-live-score-updates",
                "isHosted": False,
                "pillarId": "pillar/sport",
                "pillarName": "Sport",
            },
            {
                "id": "lifeandstyle/2024/dec/10/us-new-years-resolution",
                "type": "article",
                "sectionId": "lifeandstyle",
                "sectionName": "Life and style",
                "webPublicationDate": "2024-12-10T17:01:52Z",
                "webTitle": "People in the US: tell us about a New Year’s resolution that actually stuck",
                "webUrl": "https://www.theguardian.com/lifeandstyle/2024/dec/10/us-new-years-resolution",
                "apiUrl": "https://content.guardianapis.com/lifeandstyle/2024/dec/10/us-new-years-resolution",
                "isHosted": False,
                "pillarId": "pillar/lifestyle",
                "pillarName": "Lifestyle",
            },
            {
                "id": "us-news/live/2024/dec/10/trump-biden-politics-congress-latest-updates",
                "type": "liveblog",
                "sectionId": "us-news",
                "sectionName": "US news",
                "webPublicationDate": "2024-12-10T17:00:42Z",
                "webTitle": "Lindsey Graham vows ‘transformational’ border bill as Senate committee hears harms of Trump’s mass deportation plan – live",
                "webUrl": "https://www.theguardian.com/us-news/live/2024/dec/10/trump-biden-politics-congress-latest-updates",
                "apiUrl": "https://content.guardianapis.com/us-news/live/2024/dec/10/trump-biden-politics-congress-latest-updates",
                "isHosted": False,
                "pillarId": "pillar/news",
                "pillarName": "News",
            },
            {
                "id": "film/2024/dec/10/a-complete-unknown-review-timothee-chalamets-bob-dylan-is-an-electric-revelation",
                "type": "article",
                "sectionId": "film",
                "sectionName": "Film",
                "webPublicationDate": "2024-12-10T17:00:22Z",
                "webTitle": "A Complete Unknown review – Timothée Chalamet’s Bob Dylan is an electric revelation",
                "webUrl": "https://www.theguardian.com/film/2024/dec/10/a-complete-unknown-review-timothee-chalamets-bob-dylan-is-an-electric-revelation",
                "apiUrl": "https://content.guardianapis.com/film/2024/dec/10/a-complete-unknown-review-timothee-chalamets-bob-dylan-is-an-electric-revelation",
                "isHosted": False,
                "pillarId": "pillar/arts",
                "pillarName": "Arts",
            },
            {
                "id": "world/live/2024/dec/10/syria-live-blog-updates-assad-rebel-leaders-latest-news-damascus",
                "type": "liveblog",
                "sectionId": "world",
                "sectionName": "World news",
                "webPublicationDate": "2024-12-10T16:55:57Z",
                "webTitle": "Israel claims it has destroyed Syrian fleet and will set up ‘sterile defensive zone’ – Middle East crisis live",
                "webUrl": "https://www.theguardian.com/world/live/2024/dec/10/syria-live-blog-updates-assad-rebel-leaders-latest-news-damascus",
                "apiUrl": "https://content.guardianapis.com/world/live/2024/dec/10/syria-live-blog-updates-assad-rebel-leaders-latest-news-damascus",
                "isHosted": False,
                "pillarId": "pillar/news",
                "pillarName": "News",
            },
            {
                "id": "film/2024/dec/10/28-years-later-trailer",
                "type": "article",
                "sectionId": "film",
                "sectionName": "Film",
                "webPublicationDate": "2024-12-10T16:52:28Z",
                "webTitle": "Exceedingly good needle drops: why a 1915 Kipling poem is the cherry on top of the 28 Years Later trailer",
                "webUrl": "https://www.theguardian.com/film/2024/dec/10/28-years-later-trailer",
                "apiUrl": "https://content.guardianapis.com/film/2024/dec/10/28-years-later-trailer",
                "isHosted": False,
                "pillarId": "pillar/arts",
                "pillarName": "Arts",
            },
            {
                "id": "us-news/2024/dec/10/daniel-penny-acquittal-white-vigilante-crime",
                "type": "article",
                "sectionId": "us-news",
                "sectionName": "US news",
                "webPublicationDate": "2024-12-10T16:52:23Z",
                "webTitle": "Daniel Penny’s acquittal reveals ‘double standard’ about white vigilante crime",
                "webUrl": "https://www.theguardian.com/us-news/2024/dec/10/daniel-penny-acquittal-white-vigilante-crime",
                "apiUrl": "https://content.guardianapis.com/us-news/2024/dec/10/daniel-penny-acquittal-white-vigilante-crime",
                "isHosted": False,
                "pillarId": "pillar/news",
                "pillarName": "News",
            },
            {
                "id": "culture/2024/dec/10/jon-stewart-assad-daily-show-recap",
                "type": "article",
                "sectionId": "culture",
                "sectionName": "Culture",
                "webPublicationDate": "2024-12-10T16:45:22Z",
                "webTitle": "Jon Stewart on the fall of Assad: ‘A moment in time of pure, unalloyed joy’",
                "webUrl": "https://www.theguardian.com/culture/2024/dec/10/jon-stewart-assad-daily-show-recap",
                "apiUrl": "https://content.guardianapis.com/culture/2024/dec/10/jon-stewart-assad-daily-show-recap",
                "isHosted": False,
                "pillarId": "pillar/arts",
                "pillarName": "Arts",
            },
            {
                "id": "books/2024/dec/10/writers-union-society-of-authors-calls-for-celebrity-memoir-ghostwriters",
                "type": "article",
                "sectionId": "books",
                "sectionName": "Books",
                "webPublicationDate": "2024-12-10T16:42:22Z",
                "webTitle": "Society of Authors calls for celebrity memoir ghostwriters to be credited",
                "webUrl": "https://www.theguardian.com/books/2024/dec/10/writers-union-society-of-authors-calls-for-celebrity-memoir-ghostwriters",
                "apiUrl": "https://content.guardianapis.com/books/2024/dec/10/writers-union-society-of-authors-calls-for-celebrity-memoir-ghostwriters",
                "isHosted": False,
                "pillarId": "pillar/arts",
                "pillarName": "Arts",
            },
        ],
    }
}
